import {
    BOM_MODULE_VERSION,
    CORE_MODULE_VERSION,
    ARCGIS_MODULE_VERSION,
    GOOGLEMAPS_MODULE_VERSION,
    HERE_MODULE_VERSION,
    MAPBOX_MODULE_VERSION,
    MAPLIBRE_MODULE_VERSION,
    ICON_MODULE_VERSION,
    MARKER_NATIVE_STRATEGY_MODULE_VERSION,
    MARKER_STRATEGY_MODULE_VERSION,
    GOOGLE_MAPS_SDK_VERSION,
    MAPBOX_SDK_VERSION,
    HERE_EXPLORER_SDK_VERSION,
    ARCGIS_SDK_VERSION,
    MAPLBRE_SDK_VERSION,
    KOTLIN_VERSION,
    ANDROID_MIN_SDK_VERSION,
    ANDROID_TARGET_SDK_VERSION,
    JETPACK_COMPOSE_BOM_VERSION,
    JAVA_VERSION,
    SECRETS_GRADLE_PLUGIN_VERSION,
} from '../config.ts';

export const VERSION_IDENTIFIERS: Record<string, string> = {
    'BOM_MODULE_VERSION': BOM_MODULE_VERSION,
    'CORE_MODULE_VERSION': CORE_MODULE_VERSION,
    'ARCGIS_MODULE_VERSION': ARCGIS_MODULE_VERSION,
    'GOOGLEMAPS_MODULE_VERSION': GOOGLEMAPS_MODULE_VERSION,
    'HERE_MODULE_VERSION': HERE_MODULE_VERSION,
    'MAPBOX_MODULE_VERSION': MAPBOX_MODULE_VERSION,
    'MAPLIBRE_MODULE_VERSION': MAPLIBRE_MODULE_VERSION,
    'ICON_MODULE_VERSION': ICON_MODULE_VERSION,
    'MARKER_NATIVE_STRATEGY_MODULE_VERSION': MARKER_NATIVE_STRATEGY_MODULE_VERSION,
    'MARKER_STRATEGY_MODULE_VERSION': MARKER_STRATEGY_MODULE_VERSION,
    'GOOGLE_MAPS_SDK_VERSION': GOOGLE_MAPS_SDK_VERSION,
    'MAPBOX_SDK_VERSION': MAPBOX_SDK_VERSION,
    'HERE_EXPLORER_SDK_VERSION': HERE_EXPLORER_SDK_VERSION,
    'ARCGIS_SDK_VERSION': ARCGIS_SDK_VERSION,
    'MAPLBRE_SDK_VERSION': MAPLBRE_SDK_VERSION,
    'KOTLIN_VERSION': KOTLIN_VERSION,
    'ANDROID_MIN_SDK_VERSION': ANDROID_MIN_SDK_VERSION,
    'ANDROID_TARGET_SDK_VERSION': ANDROID_TARGET_SDK_VERSION,
    'JETPACK_COMPOSE_BOM_VERSION': JETPACK_COMPOSE_BOM_VERSION,
    'JAVA_VERSION': JAVA_VERSION,
    'SECRETS_GRADLE_PLUGIN_VERSION': SECRETS_GRADLE_PLUGIN_VERSION,
};

export function replaceVersions(str: string): string {
    let result = str;
    for (const [placeholder, value] of Object.entries(VERSION_IDENTIFIERS)) {
        result = result.replaceAll(`{${placeholder}}`, value);
        result = result.replaceAll(placeholder, value);
    }
    return result;
}
